language: java

jdk:
  - oraclejdk7
  - openjdk6
  
branches:
  only:
    - master
    - /^release-.*$/

after_success:
  - chmod +x .config/publish-javadoc.sh
  - .config/publish-javadoc.sh
  #- .config/publish-artifacts.sh