language: java
jdk:
- oraclejdk7
- openjdk6
env:
  global:
  - secure: HdbakEISUvs1xhgcLN1i/jE2ad0m6M/mSEKFrXzt8Xl6Bk0pjU2kXLZuXeGU+1cfgcxrO/GrC9DdG6lHsJgNWCPQklp02NAalmBG8UvSRsnmuZBh4zq7Mlbyj1zdSYMQHv7PeebESZzbrqDzJVSUXvC6azFPyXR1iNfoSjIEaMw=
  - secure: OGvPJ/e666wfu+jsD5RpclJvns4zpFx0+leu6xQ16NrXt4Cv/gkVFRAOialrKFm2pJxz8H2UUuI5GiSg9NphSfrSSWbNw4ucJ2hiX7EnwuhTuXTgEu1NY2lW/jgHZO4T/o9Pofh+rMvapoi9gv88qEB91gd2rmEPoD0PYI3l29o=
  - secure: Px5PZbYfRo/U6z9rJv2bBEIi19fz/vHss9DTPNh/e+zolxqwsZxeYSw2ubthD0C3Smbwp96xgQvnMvzhi6sML8/Bot8NGk9mOB5chEw6QGlSW1h6pHoxIBh+HVhV8F41QF5qN9HvCQALfeEIOeKWSDFNU7SapxmAilBwzXhjz/4=
branches:
  only:
  - master
  - development
after_success:
- mvn javadoc:aggregate
- chmod +x .config/publish-javadoc.sh
- .config/publish-javadoc.sh
- chmod +x .config/deploy-artifacts.sh
- .config/deploy-artifacts.sh
