language: java

jdk:
  - oraclejdk7
  - openjdk6

env:
  global:
  - secure: "HdbakEISUvs1xhgcLN1i/jE2ad0m6M/mSEKFrXzt8Xl6Bk0pjU2kXLZuXeGU+1cfgcxrO/GrC9DdG6lHsJgNWCPQklp02NAalmBG8UvSRsnmuZBh4zq7Mlbyj1zdSYMQHv7PeebESZzbrqDzJVSUXvC6azFPyXR1iNfoSjIEaMw="
  
branches:
  only:
    - master
    - /^release-.*$/

after_success:
  - mvn javadoc:aggregate
  - chmod +x .config/publish-javadoc.sh
  - .config/publish-javadoc.sh
  #- .config/publish-artifacts.sh